### ISSUE TITLE
ToRs vs Incoming Mobilities

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-api-tors#3]
Recently, a couple of things happened:

* Transcripts of Records API has been renamed to Incoming Mobility ToRs API. This was done to highlight the fact that this API can (currently) expose only ToRs connected to some given mobility (identified by `omobility_id`). In other words, the Receiving HEI cannot publish ToRs, for which `omobility_id` is unknown.

* In parallel, some developers suggested that perhaps EWP *should* allow to exchange ToRs *without* the context of the mobility. This however is impossible via the current API. Perhaps a separate API needs to be introduced, or the existing one should be changed.

* Again, in parallel, Incoming Mobilities API was introduced, as the result of [Ghent's proposal](https://github.com/erasmus-without-paper/ewp-specs-api-omobilities/issues/27).

All these events are related, and they introduce many new questions. For example:

* Should we consider merging *Incoming Mobility ToRs API* with *Incoming Mobilities API*? This would make sense, because these ToRs are in fact part of Incoming Mobilities. Both entities are identified by `omobility_id`.

* Should we consider adding another API for retrieving ToRs unrelated to mobilities? How would we identify such ToRs? Should we keep the *Incoming Mobility ToRs API* in this case? Or, perhaps, we could simply include the newly introduced `tor_ids` in the *Incoming Mobilities API*, and **remove** the *Incoming Mobility ToRs API*?

This seems like a topic to be discussed in a public meeting.

**Comment by janinamincer-daszkiewicz** [comment]
ToRs unrelated to mobilities (so called 'unbounded' ToRs) are discussed in https://github.com/erasmus-without-paper/general-issues/issues/28.
