### ISSUE TITLE
Signing the ELMO in ToRs API

### ISSUE THREAD

**Issue by MartaJuzepczuk** [erasmus-without-paper/ewp-specs-api-tors#7]
Current ToRs API specification says:
> This API does not currently specify how the ELMO response needs to be signed. In EMREX, ELMO files need to be signed with a very specific certificate, but in EWP the certificate used does not (currently) matter, because clients use other ways of verifying that the response came from appropriate source. This means that clients MAY simply ignore the attached digital signature (it is okay to not verify it in any way).
That said, it seems that the best certificate to use for this, would be the same certificate which was used to actually serve the ToRs API. (Clients SHOULD NOT rely on this recommendation however, because it MAY change in the future.)

If the certificate does not matter and client may ignore them, maybe we could allow servers not to send a signature at all here?

**Comment by wrygiel** [comment]
This might require changes in the ELMO specification. AFAIR, an `<elmo>` element is required to have one.

**Comment by MartaJuzepczuk** [comment]
Yes, it is required in ELMO. But maybe we could allow to send an empty signature?

**Comment by wrygiel** [comment]
Technically, we would be breaking ELMO spec by doing that. Even if it
passes XSD validation (not sure if it will), there's still the fact that
it's required in the comments. So it's a bit ugly.

A "proper" way of fixing it (if we want a really clean solution) would be
modifying ELMO specs and EMREX specs. ELMO would make it optional, while
EMREX would override it by making it required (only when ELMO is used in
EMREX).

**Comment by MartaJuzepczuk** [comment]
We don't follow the ELMO specification already. In the comment (ELMO specs) we have:
> The key used by the NCP for signing MUST match the key which has been previously published in EMREG (for this particular NCP).

**Comment by wrygiel** [comment]
Yes, possible... this particular spec is a bit too much bound with EMREX. It might be possible to modify them to allow other apps, but it's not obvious how to do that.

**Comment by mkurzydlowski** [comment]
I agree that for a clean solution ELMO should be modified to fit both EMREX and EWP but I expect it won't be changed in the near future. I suppose that we currently need to specify in EWP that we don't need nor require signature.

**Comment by janinamincer-daszkiewicz** [comment]
Geir, Matija, EWP needs changes in the specification of ELMO. ELMO should not contain obligatory signature, so it should either be made optional or taken off the ELMO. The best for EWP would be something like that:

```
<signed-elmo>
    <elmo>
        ...
    </elmo>
    <signature>
        ...
    </signature>
</signed-elmo>
```

Could such changes be made?

**Comment by mpuzar** [comment]
I see no problem in making the signature optional (we can make it effective from 1.5) and keep the comment saying that in EMREX it needs to be signed.
I wouldn't do any other changes though.

**Comment by janinamincer-daszkiewicz** [comment]
That's enough for EWP. Is 1.5 alreday public? Can we reference it from EWP?

**Comment by mpuzar** [comment]
It is public, but not released yet (waiting for feedback on the proposed changes).
You can test it by referring directly to 1.5

**Comment by janinamincer-daszkiewicz** [comment]
When could you make changes?
When do you plan to make 1.5 public?
Could it be before the end of EWP 2.0?

**Comment by janinamincer-daszkiewicz** [comment]
ELMO 1.5.0 has been released: https://github.com/emrex-eu/elmo-schemas/releases/tag/v1.5.0
