### ISSUE TITLE
F grade in gradeConversionTable

### ISSUE THREAD

**Issue by jiripetrzelka** [erasmus-without-paper/ewp-specs-api-tors#9]
Why does the conversion table in the example below contains the F grade?

https://github.com/erasmus-without-paper/ewp-specs-api-imobility-tors/blob/d051d8a66b7fa86624590109529669832a31d4d4/endpoints/get-response-example.xml#L98

when according to http://egracons.eu/sites/default/files/Grading_Table_General_Intro_0.pdf fail marks should be left out?

![image](https://user-images.githubusercontent.com/1330161/132367983-e1ed9fee-bace-4598-b531-4a9025b15fe7.png)

![image](https://user-images.githubusercontent.com/1330161/132368422-a54073c9-76c8-45b1-818d-0524bc21eca5.png)

**Comment by janinamincer-daszkiewicz** [comment]
Because it can be reused in other scenarios?

**Comment by jiripetrzelka** [comment]
If you leave the option to include or not include the fail grade open then the client script may not be able to determine whether the fail grade is or isn't included in the distribution if the university doesn't use ECTS. And if the client script doesn't know this it cannot re-calculate the distribution of pass grades without the fail grade (so that their sum is 100 %), which means it cannot do the automatic grades conversion. It would need to have an additional knowledge of all the grading schemes used in Europe with the information which grade corresponds to the fail grade (for ECTS, it would suffice to hard-code that it is the "F" value).

Also, I think that it should be specified whether the grades should start with the best or with the worst grade. Otherwise, the conversion will have to be semi-automatic because someone on the recipient side will have to input this information into the conversion script manually for schemes other than ECTS.

Or am I missing something?

If not, it appears to me that the gradeFrequency element should have an attribute for specifying whether it represents a fail grade or not.

**Comment by jiripetrzelka** [comment]
I think that the documentation should also stress that the grades must start with the worst grade and end with the best grade.

**Comment by janinamincer-daszkiewicz** [comment]
Why is that important?

**Comment by jiripetrzelka** [comment]
I imagine that once we start implementing the scripts that will do the actual conversion of grades for the recognition purposes, the script will have pair the received histogram of grades with some internal histogram in order to calculate the recognized grade but if the script does not know where the lowest value and where the highest value is, it may do it the opposite way and arrive at incorrect results. For example, it could match your grade 5! with the ECTS F grade, not with the ECTS A grade.

**Comment by mkurzydlowski** [comment]
A cumulative distribution is by definition a function that describes "the probability that X will take a value less than or equal to x", so it should be clear enough that "lower" grades are the ones we start with.

What's more, the linked Egracons PDF is full of examples that make this clear for less technical persons.

**Comment by janinamincer-daszkiewicz** [comment]
Yes, that's true, let's not explain in our specifications official definition.
